In [3]:
import numpy as np

1、创建一个长度为10的全0数组

In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

2、创建一个3*5的全1的数组

In [5]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

3、创建一个相同值的3*5的数组

In [6]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

4、创建一个线性数组，0开始，步长2，到20结束，不包括20

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

5、创建一个5个元素内容为0-1之间均匀分布的数组

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6、创建一个0-1之间的随机数4*5的数组

In [9]:
np.random.random((4,5))

array([[0.58638455, 0.15938809, 0.85482842, 0.71686558, 0.00717057],
       [0.53076027, 0.21240451, 0.08219764, 0.15989077, 0.42604246],
       [0.96035047, 0.24167462, 0.73097701, 0.2858824 , 0.60991321],
       [0.01252617, 0.3543025 , 0.13684894, 0.05500898, 0.30429486]])

7、创建一个3*4，均值为0，标准差为1的 正太分布的随机数数组

In [10]:
np.random.normal(0,1,(3,4))

array([[ 2.0800437 , -0.7016455 , -0.46611356,  1.19219649],
       [-0.22015727,  0.12023594, -1.14315993, -1.06172002],
       [ 0.07401672, -1.2139866 ,  0.00344751, -0.36476886]])

8、创建随机3*4的[0-10)的整数数组

In [11]:
np.random.randint(0,10,(3,4))

array([[6, 7, 7, 5],
       [2, 4, 2, 0],
       [7, 7, 4, 9]])

9、创建一个9*9的单位矩阵

In [12]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

10、创建一个3*10为初始哈的数组

In [16]:
np.empty((3,4))

array([[2.0800437 , 0.7016455 , 0.46611356, 1.19219649],
       [0.22015727, 0.12023594, 1.14315993, 1.06172002],
       [0.07401672, 1.2139866 , 0.00344751, 0.36476886]])