In [1]:
import numpy as np

In [6]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


加减乘除

In [7]:
print(x+1)
print(x-1)
print(x*2)
print(x/2)

[ 1  2  3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6  7  8]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


绝对值

In [9]:
np.abs(x-5)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

三角函数

In [15]:
theta = np.linspace(0,np.pi,3)

In [16]:
print("theta=",theta)
print("sin(theta)=",np.sin(theta))
print("cos(theta)=",np.cos(theta))
print("tan(theta)=",np.tan(theta))

theta= [0.         1.57079633 3.14159265]
sin(theta)= [0.00000000e+00 1.00000000e+00 1.22460635e-16]
cos(theta)= [ 1.00000000e+00  6.12303177e-17 -1.00000000e+00]
tan(theta)= [ 0.00000000e+00  1.63317787e+16 -1.22460635e-16]


逆三角函数

In [17]:
x = [-1,0,1]
print("x=",theta)
print("arcsin(x)=",np.arcsin(x))
print("arccos(x)=",np.arccos(x))
print("arctan(x)=",np.arctan(x))

x= [0.         1.57079633 3.14159265]
arcsin(x)= [-1.57079633  0.          1.57079633]
arccos(x)= [3.14159265 1.57079633 0.        ]
arctan(x)= [-0.78539816  0.          0.78539816]


指数和对数

In [19]:
x = [1,2,3]
print("x=",x)
print("e^x=",np.exp(x))
print("2^x=",np.exp2(x))
print("3^x=",np.power(3,x))

x= [1, 2, 3]
e^x= [ 2.71828183  7.3890561  20.08553692]
2^x= [2. 4. 8.]
3^x= [ 3  9 27]


In [22]:
x = [1,2,4,10]
print("x=",x)
print("ln(x)=",np.log(x))
print("log2(x)=",np.log2(x))
print("log10(x)=",np.log10(x))

x= [1, 2, 4, 10]
ln(x)= [0.         0.69314718 1.38629436 2.30258509]
log2(x)= [0.         1.         2.         3.32192809]
log10(x)= [0.         0.30103    0.60205999 1.        ]


指数对数特殊版，非常小的数计算更精确

In [24]:
x = [0,0.001,0.01,0.1]
print("x=",x)
print("exp(x)-1=",np.expm1(x))
print("log(1+x)=",np.log1p(x))

x= [0, 0.001, 0.01, 0.1]
exp(x)-1= [0.         0.0010005  0.01005017 0.10517092]
log(1+x)= [0.         0.0009995  0.00995033 0.09531018]
