In [1]:
import numpy as np

In [2]:
x = np.arange(3)
print(x)

[0 1 2]


In [3]:
x+3

array([3, 4, 5])

In [4]:
y = np.ones((3,3))

In [5]:
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
x+y

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
z = x[:,np.newaxis]
print(z)

[[0]
 [1]
 [2]]


In [8]:
x+z

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [9]:
y+z

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [10]:
x+y

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [11]:
z+2

array([[2],
       [3],
       [4]])

规则：

* 规则 1:如果两个数组的维度数不相同，那么小维度数组的形状将会在最左边补 1。
* 规则 2:如果两个数组的形状在任何一个维度上都不匹配，那么数组的形状会沿着维度为 1 的维度扩展以匹配另外一个数组的形状。
* 规则 3:如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度等于 1，那么会引发异常。

![image](images/guangbao.png)

例1：

In [15]:
x = np.ones((2,3))
print(x)
y = np.arange(3)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [16]:
print(x.shape,y.shape)

(2, 3) (3,)


根据规则 1，数组 a 的维度数更小，所以在其左边补 1:
这里因为y维度小，所以将y的左边加1即相当于
    
```
y = y.reshape((1,3))
print(y.shape)
```

根据规则 2，第一个维度不匹配，因此扩展这个维度以匹配数组: x.shape -> (2, 3)   y.shape -> (2, 3)

In [21]:
x+y

array([[1., 2., 3.],
       [1., 2., 3.]])

例2：

In [24]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a,b)
print(a.shape,b.shape)

[[0]
 [1]
 [2]] [0 1 2]
(3, 1) (3,)


规则 1 告诉我们，需要用 1 将 b 的形状补全:
规则 2 告诉我们，需要更新这两个数组的维度来相互匹配:
因为结果匹配，所以这两个形状是兼容的，可以看到以下结果:

In [25]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])