In [16]:
import numpy as np

In [17]:
a = np.random.random(size=(10,3))
print(a)

[[0.08229957 0.75046651 0.47342119]
 [0.0266124  0.12601663 0.2385181 ]
 [0.14945965 0.03231239 0.90736704]
 [0.87563407 0.60327961 0.9955092 ]
 [0.43979316 0.06359614 0.022718  ]
 [0.82567556 0.65761391 0.37928567]
 [0.37813645 0.31604295 0.51622387]
 [0.70525122 0.60214802 0.79190409]
 [0.48362808 0.1335137  0.54393551]
 [0.7386096  0.94427711 0.828711  ]]


In [18]:
x = a.mean(0)
print(x)

[0.47050998 0.4229267  0.56975936]


In [19]:
y = a.mean(axis=1)
print(y)

[0.43539576 0.13038237 0.36304636 0.82480763 0.1753691  0.62085838
 0.40346776 0.69976778 0.38702576 0.83719924]


In [21]:
m = a-x
print(m)

[[-0.3882104   0.32753981 -0.09633818]
 [-0.44389758 -0.29691007 -0.33124127]
 [-0.32105033 -0.39061431  0.33760767]
 [ 0.40512409  0.18035292  0.42574983]
 [-0.03071681 -0.35933056 -0.54704136]
 [ 0.35516559  0.23468721 -0.1904737 ]
 [-0.09237353 -0.10688374 -0.05353549]
 [ 0.23474124  0.17922133  0.22214472]
 [ 0.0131181  -0.289413   -0.02582386]
 [ 0.26809962  0.52135042  0.25895163]]


a-y是不行的，因为广播规则，
a.shape->(10,3)
y.shape->(10,)->(1,10)
不匹配，报错

In [22]:
m.mean(0)

array([ 1.11022302e-17, -6.66133815e-17,  5.55111512e-17])