In [1]:
import numpy as np

和通用函数类似的比较操作

In [18]:
x = np.random.randint(0,10,(5,5))
print(x)

[[7 5 8 2 1]
 [1 3 3 1 3]
 [1 5 9 2 6]
 [3 5 1 9 9]
 [2 1 9 2 2]]


In [25]:
x<5

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False, False,  True, False],
       [ True, False,  True, False, False],
       [ True,  True, False,  True,  True]])

操作布尔数组

In [26]:
np.count_nonzero(x<5)

15

因为false会是0 true=1，所以,并且可以按行、列统计

In [30]:
np.sum(x<5)

15

In [31]:
np.sum(x<5,axis=0)

array([4, 2, 2, 4, 3])

In [32]:
np.sum(x<5,axis=1)

array([2, 5, 2, 2, 4])

np.all() 和 np.any() 也可以用于沿着特定的坐标轴

判断是否有

In [38]:
np.any(x<5)

True

In [39]:
np.any(x>100)

False

判断是否都是

In [40]:
np.all(x<5)

False

In [41]:
np.all(x<100)

True

支持组合 &、|、^ 和 ~ 

In [48]:
np.sum((x>2) & (x<5))

4

|运算符|对应函数|
|--|--|
|& |np.bitwise_and |
||| np.bitwise_or| 
|^| np.bitwise_xor|
|~| np.bitwise_not|

将布尔数组作为掩码

In [49]:
x[x<5]

array([2, 1, 1, 3, 3, 1, 3, 1, 2, 3, 1, 2, 1, 2, 2])

In [50]:
x[(x<8)&(x>3)]

array([7, 5, 5, 6, 5])