In [1]:
import numpy as np

In [4]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [6]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [10]:
print(data['name'])

['Alice' 'Bob' 'Cathy' 'Doug']


In [11]:
print(data[0])

('Alice', 25, 55.)


In [12]:
print(data[0]['name'])

Alice


In [14]:
np.dtype({'names':('name', 'age', 'weight'),'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

|numpy类型符合|说明|示例|
|--|--|--|
|'b'| 字节型|np.dtype('b')|
|'i' |有符号整型 |np.dtype('i4') == np.int32|
|'u' |无符号整型 | np.dtype('u1') == np.uint8|
|'f' 浮点型|np.dtype('f8') == np.int64|
|'c' |复数浮点型 |np.dtype('c16') == np.complex128|
|'S'、'a' 字符串|np.dtype('S5')|
|'U' |Unicode 编码字符串|np.dtype('U') == np.str_|
|'V' |原生数据，raw data(空，void)| np.dtype('V') == np.void|

   


结构化数据---复合

In [17]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print("\n\n")
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


数组扭转为np.recarray（一个有域概念的类型，详细可以?查看，效率提升）

In [24]:
data['age']

array([25, 45, 37, 19])

In [25]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [26]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])

In [27]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

468 ns ± 0.522 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
11.7 µs ± 18.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
15.6 µs ± 25.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
data_rec[0]

('Alice', 25, 55.)